name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  stresstest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: install dependencies
      run: |
        pip3 install tqdm
    - name: stresstest
      run: /usr/bin/time ./stresstest.py

  bench:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: benchmark
      run: /usr/bin/time ./bench.sh