name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  correctness_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: install dependencies
      run: |
        ./scripts/install_dependencies.sh
    - name: build
      run: |
        cmake -B build
        cd build
        make
    - name: small_graph_test
      run: |
        cd build
        ./small_graph_test.out 2> err.log || tail err.log
    - name: stresstest
      run: |
        cd build
        python3 ../scripts/stresstest.py

  eval:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: install dependencies
      run: |
        ./scripts/install_dependencies.sh
    - name: build
      run: |
        cmake -B build
        cd build
        make
    - name: eval
      run: |
        set +e
        cd scripts
        /usr/bin/time ./run_all.sh ../build/main.out ../in/PACE2025-instances/ds/exact 600
        python3 report.py .solutions
        cat summary.csv