name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_all_small_graphs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: install dependencies
      run: |
        wget https://packages.gurobi.com/12.0/gurobi12.0.1_linux64.tar.gz
        mv gurobi12.0.1_linux64.tar.gz src/ext
        cd src/ext
        tar -xvzf gurobi10.0.3_linux64.tar.gz
    - name: small_graph_test
      run: |
        cmake .
        make small_graph_test
        ./small_graph_test.out 2> err.log || tail err.log
  stresstest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: install dependencies
      run: |
        pip3 install tqdm
        wget https://packages.gurobi.com/12.0/gurobi12.0.1_linux64.tar.gz
        mv gurobi12.0.1_linux64.tar.gz src/ext
        cd src/ext
        tar -xvzf gurobi10.0.3_linux64.tar.gz
    - name: stresstest
      run: /usr/bin/time ./stresstest.py
  eval:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: install dependencies
      run: |
        wget https://packages.gurobi.com/12.0/gurobi12.0.1_linux64.tar.gz
        mv gurobi12.0.1_linux64.tar.gz src/ext
        cd src/ext
        tar -xvzf gurobi10.0.3_linux64.tar.gz
    - name: eval
      run: |
        set +e
        /usr/bin/time ./eval_all.sh