name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  stresstest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build
        git clone https://github.com/mabseher/htd/
        cd htd
        cmake .
        sudo make
        sudo make install
    - name: stresstest
      run: /usr/bin/time ./stresstest.sh

  bench:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build
        git clone https://github.com/mabseher/htd/
        cd htd
        cmake .
        sudo make
        sudo make install
    - name: benchmark
      run: /usr/bin/time ./bench.sh