name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  install-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build
        git clone https://github.com/mabseher/htd/
        cd htd
        cmake .
        sudo make install

  stresstest:
    needs: install-and-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: |
        cmake .
        make
    - name: stresstest
      run: time ./stresstest.sh

  bench:
    needs: install-and-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: |
        cmake .
        make
    - name: make bench
      run: time ./bench.sh