name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  correctness_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: install dependencies
      run: |
        ./scripts/install_dependencies.sh
        pip3 install tqdm
    - name: build
      run: |
        cmake -DCMAKE_BUILD_TYPE=Testing -B build
        cd build
        make
    - name: small_graph_test
      run: |
        cd build
        ./small_graph_test.out 2> err.log || tail err.log
    - name: stresstest
      run: |
        cd build
        python3 ../scripts/stresstest.py
